 echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo -e "\033[33m                                                                                                    "
echo -e "\033[33m                                                                                                    "
echo -e "\033[33m                                         ##################                                         "
echo -e "\033[33m                                    ############################                                    "
echo -e "\033[33m                                 ##################################                                 "
echo -e "\033[33m                               ######################################                               "
echo -e "\033[33m                             ##########################################                             "
echo -e "\033[33m                           ##############################################                           "
echo -e "\033[33m                         ##################################################                         "
echo -e "\033[91m                        ####################################################                        "
echo -e "\033[91m                       ######################################################                       "
echo -e "\033[91m                      ########################################################                      "
echo -e "\033[91m                     ##########################################################                     "
echo -e "\033[91m                     ##########################################################                     "
echo -e "\033[91m                     ##########################################################                     "
echo -e "\033[97m        /yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-       "
echo -e "\033[33m        ######################################################################################      "
echo -e "\033[33m        ######################################################################################      "
echo -e "\033[97m        -ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd/       "
echo -e "\033[97m                      hm            -mmmmm-              -mmmmmm-           oM:                     "
echo -e "\033[97m                      /M/         /hmNMMMNmy:          -sdNNMMNmh+'        'md                      "
echo -e "\033[97m                      'dm'       yMMMMMMMMMMNy        +NMMMMMMMMMMd-       sN:                      "
echo -e "\033[97m                       -Ny'     +MMMMMMMMMMMMMy      .MMMMMMMMMMMMMd      /No                       "
echo -e "\033[97m                        :Ns'    oMMMMMMMMMMMMMm      :MMMMMMMMMMMMMN'    /Ns'                       "
echo -e "\033[97m                         :my'   .mMMMMMMMMMMMM+      'mMMMMMMMMMMMMs   '+No'                        "
echo -e "\033[97m                          .hd:   -hMMMMMMMMMm+        -dMMMMMMMMMNs'  .hm/                          "
echo -e "\033[97m                           '+ds.  ':ydmmmdy+.    ...   ':shmmmmdo-  .omy.                           "
echo -e "\033[97m                             .ods-  'mmmm'      pNNNq    '-mmmm-' -odh:                             "
echo -e "\033[97m                               .omdo-'          bmmmd         '-+hmy-                               "
echo -e "\033[97m                               '+dMNhhyo:-.''    '.'   ''.-:oyhdMNd/'                               "
echo -e "\033[97m                                ssN    'sysysysysysysysysysy'   ym/                                 "
echo -e "\033[97m                                smd,     sy      sy      sy      Ns                                 "
echo -e "\033[97m                                +dsysysysys      sy      sy  ,:+sdN-                                "
echo -e "\033[97m                                dd    sysys      sy      sysysd   No                                "
echo -e "\033[97m                                Nh.     sy:/+sysysysysy+/sy.      hh                                "
echo -e "\033[97m                                Myhy+,,:sy       sy      sy:   :shmm                                "
echo -e "\033[97m                                M/ :/yhyNo.      sy      syhshhs'.+M                                "
echo -e "\033[97m                                my     'sysysysysysysysysysys'    yd                                "
echo -e "\033[97m                                +N.           '.......'          'N/                                "
echo -e "\033[97m                                'hh'                             yh'                                "
echo -e "\033[97m                                 'hh'                          'yd'                                 "
echo -e "\033[97m                                  'sd/'                       :ds'                                  "
echo -e "\033[97m                                    .sdo-                  .+hs.                                    "
echo -e "\033[97m                                      '/shyo/:-.,,,,..:/oyys:'                                      "
echo -e "\033[97m                                          '-:+ossssso+/:.'                                          "
echo -e "\033[97m"
echo -e "\033[97m                   ██████╗ ███╗   ██╗███████╗    ██████╗ ██╗███████╗ ██████╗███████╗"
echo -e "\033[97m                  ██╔═══██╗████╗  ██║██╔════╝    ██╔══██╗██║██╔════╝██╔════╝██╔════╝"
echo -e "\033[97m                  ██║   ██║██╔██╗ ██║█████╗█████╗██████╔╝██║█████╗  ██║     █████╗  "
echo -e "\033[97m                  ██║   ██║██║╚██╗██║██╔══╝╚════╝██╔═══╝ ██║██╔══╝  ██║     ██╔══╝  "
echo -e "\033[97m                  ╚██████╔╝██║ ╚████║███████╗    ██║     ██║███████╗╚██████╗███████╗"
echo -e "\033[97m                   ╚═════╝ ╚═╝  ╚═══╝╚══════╝    ╚═╝     ╚═╝╚══════╝ ╚═════╝╚══════╝"
echo -e "\033[97m"
echo -e "\033[97m"
                                                                    
                                                                    
                                                                    
