#!/usr/bin/php
<?php

/*
 * Color List
 * ----------------------------------------
 * 
 * Black        0;30     Dark Gray     1;30
 * Red          0;31     Light Red     1;31
 * Green        0;32     Light Green   1;32
 * Brown/Orange 0;33     Yellow        1;33
 * Blue         0;34     Light Blue    1;34
 * Purple       0;35     Light Purple  1;35
 * Cyan         0;36     Light Cyan    1;36
 * Light Gray   0;37     White         1;37
 */


$list = (object)[
    'ERROR'     => '1;31',
    'WARNING'   => '1;33',
    'WARN'	=> '1;33',
    'DEBUG'	=> '1;34',
    'INFO'      => '1;32',
];


$in = fopen('php://stdin', 'r');

while(!feof($in)){
    $x = fgets($in);
    foreach($list as $k => $v){
        if(strpos(strtoupper($x), $k) !== false){
            echo "\033[{$list->$k}m";
            break;
        }
    }
    echo $x;
}

fclose($in);
echo "\033[1;37m";
